# Generated by Django 6.0.1 on 2026-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('image_url', models.CharField(default='https://via.placeholder.com/300', max_length=2083)),
            ],
        ),
    ]
